.PHONY: clean All

All:
	@echo "----------Building project:[ madac - Debug ]----------"
	@cd "madac" && "$(MAKE)" -f  "madac.mk"
clean:
	@echo "----------Cleaning project:[ madac - Debug ]----------"
	@cd "madac" && "$(MAKE)" -f  "madac.mk" clean
